### ISSUE TITLE
Unable to request the api from the background

### ISSUE THREAD

**Issue by Cjzz65535** [mohammad-hosein-shahpouri/AspNetCore.SpaServices.ViteDevelopmentServer#1]
As readme successfully integrated vite with asp.net core my asp.net core is a webapi project and when I use the following code my api request is not work

**Without using the middleware, the api can be used**
![PixPin_2024-06-25_15-32-32](https://github.com/mohammad-hosein-shahpouri/AspNetCore.SpaServices.ViteDevelopmentServer/assets/96868835/beeeeba7-33bc-4a4c-93f3-4c022edf5a3b)

**With this spa middleware, the api is not accessible**
![image](https://github.com/mohammad-hosein-shahpouri/AspNetCore.SpaServices.ViteDevelopmentServer/assets/96868835/c0b09ae6-e46e-425b-9294-4793f2b09e8c)

**Comment by mohammad-hosein-shahpouri** [comment]
Instead of using `app.MapControlles();`, use `app.UseEndpoints(_ => { });` before UseSpa middleware. like
```csharp
app.UseEndpoints(_ => { });

app.UseSpa(spa =>
{
    spa.Options.SourcePath = "ClientApp";

    if (isDevelopment) spa.UseViteDevelopmentServer("dev");
});

app.Run();
```
